namespace AutoServiceLab.Domain.Enums;

public enum CarBrand
{
    Toyota = 0,
    BMW = 1,
    Mercedes = 2,
    Audi = 3,
    Volkswagen = 4,
    Ford = 5,
    Hyundai = 6,
    Kia = 7,
    Nissan = 8,
    Honda = 9,
    Lexus = 10,
    Volvo = 11,
    Mazda = 12,
    Subaru = 13,
    Mitsubishi = 14,
    Chevrolet = 15,
    Renault = 16,
    Peugeot = 17,
    Citroen = 18,
    Skoda = 19,
    Seat = 20,
    Opel = 21,
    Fiat = 22,
    LandRover = 23,
    Jaguar = 24,
    Porsche = 25,
    Tesla = 26,
    Infiniti = 27,
    Acura = 28,
    Suzuki = 29,
    Jeep = 30,
    Dodge = 31,
    Chrysler = 32,
    Cadillac = 33,
    Buick = 34,
    Genesis = 35,
    Chery = 36,
    Geely = 37,
    Haval = 38,
    Exeed = 39,
    Lada = 40
}
